let racasCachorros = [
    {
        raca: "Shih Tzu",
        expectativaDeVida: 12,
        altura: 25,
        peso: 5,
        temperamento: "Alegre, brincalhão, leal e adaptável.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Idosos, solteiros, apartamentos",
        pontosDeAtencao: "Pelagem, olhos, dentes, obesidade",
        id: "shihtzu"
    },
    {
        raca: "Golden Retriever",
        expectativaDeVida: 12,
        altura: 55,
        peso: 30,
        temperamento: "Amigável, leal, paciente e inteligente.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias com crianças, pessoas ativas",
        pontosDeAtencao: "Displasia coxofemoral, otite externa",
        id: "retriever-golden"
    },
    {
        raca: "Labrador Retriever",
        expectativaDeVida: 12,
        altura: 55,
        peso: 30,
        temperamento: "Amigável, enérgico, inteligente.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias com crianças, atividades ao ar livre",
        pontosDeAtencao: "Obesidade, displasia coxofemoral",
        id: "labrador"
    },
    {
        raca: "Pastor Alemão",
        expectativaDeVida: 13,
        altura: 60,
        peso: 30,
        temperamento: "Inteligente, leal, protetor e trabalhador.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias ativas, trabalho policial",
        pontosDeAtencao: "Displasia coxofemoral, problemas de saúde oculares",
        id: "germanshepherd"
    },
    {
        raca: "Beagle",
        expectativaDeVida: 15,
        altura: 38,
        peso: 10,
        temperamento: "Alegre, curioso, sociável e amigável.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Médio",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias, caça",
        pontosDeAtencao: "Obesidade, problemas de pele",
        id: "beagle"
    },
    {
        raca: "Bulldog Francês",
        expectativaDeVida: 10,
        altura: 25,
        peso: 10,
        temperamento: "Carinhoso, brincalhão, adaptável e calmo.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas respiratórios, problemas de pele",
        id: "bulldog-french"
    },
    {
        raca: "Pug",
        expectativaDeVida: 13,
        altura: 30,
        peso: 6,
        temperamento: "Alegre, brincalhão, charmoso e leal.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas respiratórios, obesidade",
        id: "pug"
    },
    {
        raca: "Yorkshire Terrier",
        expectativaDeVida: 15,
        altura: 20,
        peso: 3,
        temperamento: "Valente, inteligente, alerta e leal.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas solitárias",
        pontosDeAtencao: "Problemas dentários, luxação de patela",
        id: "terrier-yorkshire"
    },
    {
        raca: "Chihuahua",
        expectativaDeVida: 15,
        altura: 15,
        peso: 2,
        temperamento: "Valente, alerta, leal e às vezes teimoso.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas solitárias",
        pontosDeAtencao: "Problemas dentários, luxação de patela",
        id: "https://exemplo.com/imagens/chihuahua.jpg"
    },    
    {
        raca: "Lhasa Apso",
        expectativaDeVida: 15,
        altura: 25,
        peso: 6,
        temperamento: "Independente, leal, reservado com estranhos.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas dentários, problemas oculares",
        id: "lhasa"
    },
    {
        raca: "Border Collie",
        expectativaDeVida: 14,
        altura: 53,
        peso: 20,
        temperamento: "Inteligente, ativo, enérgico e obediente.",
        nivelDeAtividade: "Muito alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Alta",
        companhiaOuSeguranca: "Trabalho",
        idealPara: "Pessoas ativas, esportes caninos",
        pontosDeAtencao: "Obesidade, problemas oculares",
        id: "collie-border"
    },
    {
        raca: "Boxer",
        expectativaDeVida: 10,
        altura: 60,
        peso: 30,
        temperamento: "Alegre, leal, protetor e brincalhão.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Médio",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias, atividades ao ar livre",
        pontosDeAtencao: "Displasia coxofemoral, problemas cardíacos",
        id: "boxer"
    },
    {
        raca: "Rottweiler",
        expectativaDeVida: 10,
        altura: 65,
        peso: 50,
        temperamento: "Leal, protetor, corajoso e calmo.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias com experiência, trabalho de guarda",
        pontosDeAtencao: "Displasia coxofemoral, problemas de saúde oculares",
        id: "rottweiler"
    },
    {
        raca: "Doberman",
        expectativaDeVida: 12,
        altura: 68,
        peso: 32,
        temperamento: "Inteligente, leal, protetor e reservado com estranhos.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias com experiência, trabalho policial",
        pontosDeAtencao: "Displasia coxofemoral, problemas cardíacos",
        id: "doberman"
    }    
];
let racasGatos = [
    {
        raca: "Siamês",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Inteligente, vocal, ativo e curioso.",
        nivelDeAtividade: "Alto",
        pelagem: "Curta, fina e brilhante",
        necessidadeDeAtencao: "Alta",
        companhiaOuSozinho: "Companhia",
        idealPara: "Pessoas ativas, apartamentos",
        pontosDeAtencao: "Problemas respiratórios em alguns casos"
    },
    {
        raca: "Persa",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e independente.",
        nivelDeAtividade: "Baixo",
        pelagem: "Longa, densa e sedosa",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Cuidados com a pelagem"
    },
    {
        raca: "Maine Coon",
        expectativaDeVida: 13,
        tamanho: "Grande",
        peso: 8,
        temperamento: "Gentil, paciente e brincalhão.",
        nivelDeAtividade: "Moderado",
        pelagem: "Longa, densa e resistente à água",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Famílias com crianças, casas com espaço"
    },
    {
        raca: "Sphynx",
        expectativaDeVida: 14,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Ativo, curioso e sociável.",
        nivelDeAtividade: "Alto",
        pelagem: "Sem pelos",
        necessidadeDeAtencao: "Alta",
        companhiaOuSozinho: "Companhia",
        idealPara: "Pessoas que gostam de gatos ativos"
    },
    {
        raca: "Ragdoll",
        expectativaDeVida: 15,
        tamanho: "Grande",
        peso: 6,
        temperamento: "Calmo, dócil e relaxado.",
        nivelDeAtividade: "Baixo",
        pelagem: "Longa, sedosa e macia",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Famílias, pessoas tranquilas"
    },
    {
        raca: "Scottish Fold",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e curioso.",
        nivelDeAtividade: "Moderado",
        pelagem: "Curta ou longa, orelhas dobradas"
    },
    {
        raca: "Bengal",
        expectativaDevida: 12,
        tamanho: "Médio",
        peso: 5,
        temperamento: "Ativo, curioso e atlético.",
        nivelDeAtividade: "Alto",
        pelagem: "Manchada, semelhante à de um leopardo"
    },
    {
        raca: "Azul Russo",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e reservado.",
        nivelDeAtividade: "Moderado",
        pelagem: "Curta, densa e prateada"
    },
    {
        raca: "British Shorthair",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 6,
        temperamento: "Calmo, gentil e independente.",
        nivelDeAtividade: "Baixo",
        pelagem: "Curta, densa e macia"
    },
    {
        raca: "Abissínio",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Ativo, curioso e inteligente.",
        nivelDeAtividade: "Alto",
        pelagem: "Curta, densa e marcada"
    }
];