let racasCachorros = [
    {
        raca: "Shih Tzu",
        expectativaDeVida: 12,
        altura: 25,
        peso: 5,
        temperamento: "Alegre, brincalhão, leal e adaptável.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Idosos, solteiros, apartamentos",
        pontosDeAtencao: "Pelagem, olhos, dentes, obesidade",
        id: "shihtzu",
        img: "shih-tzu.png"
    },
    {
        raca: "Golden Retriever",
        expectativaDeVida: 12,
        altura: 55,
        peso: 30,
        temperamento: "Amigável, leal, paciente e inteligente.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias com crianças, pessoas ativas",
        pontosDeAtencao: "Displasia coxofemoral, otite externa",
        id: "retriever-golden",
        img: "golden.png"
    },
    {
        raca: "Labrador Retriever",
        expectativaDeVida: 12,
        altura: 55,
        peso: 30,
        temperamento: "Amigável, enérgico, inteligente.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias com crianças, atividades ao ar livre",
        pontosDeAtencao: "Obesidade, displasia coxofemoral",
        id: "labrador",
        img: "labrador.png"
    },
    {
        raca: "Pastor Alemão",
        expectativaDeVida: 13,
        altura: 60,
        peso: 30,
        temperamento: "Inteligente, leal, protetor e trabalhador.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias ativas, trabalho policial",
        pontosDeAtencao: "Displasia coxofemoral, problemas de saúde oculares",
        id: "germanshepherd",
        img: "pastor.png"
    },
    {
        raca: "Beagle",
        expectativaDeVida: 15,
        altura: 38,
        peso: 10,
        temperamento: "Alegre, curioso, sociável e amigável.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Médio",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias, caça",
        pontosDeAtencao: "Obesidade, problemas de pele",
        id: "beagle",
        img: "beagle.png"
    },
    {
        raca: "Bulldog Francês",
        expectativaDeVida: 10,
        altura: 25,
        peso: 10,
        temperamento: "Carinhoso, brincalhão, adaptável e calmo.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas respiratórios, problemas de pele",
        id: "bulldog-french",
        img: "bulldog-frances.png"
    },
    {
        raca: "Pug",
        expectativaDeVida: 13,
        altura: 30,
        peso: 6,
        temperamento: "Alegre, brincalhão, charmoso e leal.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas respiratórios, obesidade",
        id: "pug",
        img: "pug.png"
    },
    {
        raca: "Yorkshire Terrier",
        expectativaDeVida: 15,
        altura: 20,
        peso: 3,
        temperamento: "Valente, inteligente, alerta e leal.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas solitárias",
        pontosDeAtencao: "Problemas dentários, luxação de patela",
        id: "terrier-yorkshire",
        img: "yorkshire.png"
    },
    {
        raca: "Chihuahua",
        expectativaDeVida: 15,
        altura: 15,
        peso: 2,
        temperamento: "Valente, alerta, leal e às vezes teimoso.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Alta",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas solitárias",
        pontosDeAtencao: "Problemas dentários, luxação de patela",
        id: "chihuahua",
        img: "chihuahua.png"
    },    
    {
        raca: "Lhasa Apso",
        expectativaDeVida: 15,
        altura: 25,
        peso: 6,
        temperamento: "Independente, leal, reservado com estranhos.",
        nivelDeAtividade: "Baixo",
        necessidadeDeEspaco: "Pequeno",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Problemas dentários, problemas oculares",
        id: "lhasa",
        img: "lhasa-apso.png"
    },
    {
        raca: "Border Collie",
        expectativaDeVida: 14,
        altura: 53,
        peso: 20,
        temperamento: "Inteligente, ativo, enérgico e obediente.",
        nivelDeAtividade: "Muito alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Alta",
        companhiaOuSeguranca: "Trabalho",
        idealPara: "Pessoas ativas, esportes caninos",
        pontosDeAtencao: "Obesidade, problemas oculares",
        id: "collie-border",
        img: "border-collie.png"
    },
    {
        raca: "Boxer",
        expectativaDeVida: 10,
        altura: 60,
        peso: 30,
        temperamento: "Alegre, leal, protetor e brincalhão.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Médio",
        atencao: "Moderada",
        companhiaOuSeguranca: "Companhia",
        idealPara: "Famílias, atividades ao ar livre",
        pontosDeAtencao: "Displasia coxofemoral, problemas cardíacos",
        id: "boxer",
        img: "boxer.png"
    },
    {
        raca: "Rottweiler",
        expectativaDeVida: 10,
        altura: 65,
        peso: 50,
        temperamento: "Leal, protetor, corajoso e calmo.",
        nivelDeAtividade: "Moderado",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias com experiência, trabalho de guarda",
        pontosDeAtencao: "Displasia coxofemoral, problemas de saúde oculares",
        id: "rottweiler",
        img: "rottweiler.png"
    },
    {
        raca: "Doberman",
        expectativaDeVida: 12,
        altura: 68,
        peso: 32,
        temperamento: "Inteligente, leal, protetor e reservado com estranhos.",
        nivelDeAtividade: "Alto",
        necessidadeDeEspaco: "Grande",
        atencao: "Moderada",
        companhiaOuSeguranca: "Segurança",
        idealPara: "Famílias com experiência, trabalho policial",
        pontosDeAtencao: "Displasia coxofemoral, problemas cardíacos",
        id: "doberman",
        img: "doberman.png"
    }    
];
let racasGatos = [
    {
        raca: "Siamês",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Inteligente, vocal, ativo e curioso.",
        nivelDeAtividade: "Alto",
        pelagem: "Curta, fina e brilhante",
        necessidadeDeAtencao: "Alta",
        companhiaOuSozinho: "Companhia",
        idealPara: "Pessoas ativas, apartamentos",
        pontosDeAtencao: "Problemas respiratórios em alguns casos",
        id: "siam",
        img: "siames.png"
    },
    {
        raca: "Persa",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e independente.",
        nivelDeAtividade: "Baixo",
        pelagem: "Longa, densa e sedosa",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Apartamentos, pessoas tranquilas",
        pontosDeAtencao: "Cuidados com a pelagem",
        id: "pers",
        img: "persa.png"
    },
    {
        raca: "Maine Coon",
        expectativaDeVida: 13,
        tamanho: "Grande",
        peso: 8,
        temperamento: "Gentil, paciente e brincalhão.",
        nivelDeAtividade: "Moderado",
        pelagem: "Longa, densa e resistente à água",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Famílias com crianças, casas com espaço",
        id: "mcoo",
        img: "maine-coon.png"
    },
    {
        raca: "Sphynx",
        expectativaDeVida: 14,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Ativo, curioso e sociável.",
        nivelDeAtividade: "Alto",
        pelagem: "Sem pelos",
        necessidadeDeAtencao: "Alta",
        companhiaOuSozinho: "Companhia",
        idealPara: "Pessoas que gostam de gatos ativos",
        id: "sphy",
        img: "sphynx.png"
    },
    {
        raca: "Ragdoll",
        expectativaDeVida: 15,
        tamanho: "Grande",
        peso: 6,
        temperamento: "Calmo, dócil e relaxado.",
        nivelDeAtividade: "Baixo",
        pelagem: "Longa, sedosa e macia",
        necessidadeDeAtencao: "Moderada",
        companhiaOuSozinho: "Ambos",
        idealPara: "Famílias, pessoas tranquilas",
        id: "ragd",
        img: "ragdoll.png"
    },
    {
        raca: "Scottish Fold",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e curioso.",
        nivelDeAtividade: "Moderado",
        pelagem: "Curta ou longa, orelhas dobradas",
        id: "sfol",
        img: "scottish-fold.png"
    },
    {
        raca: "Bengal",
        expectativaDevida: 12,
        tamanho: "Médio",
        peso: 5,
        temperamento: "Ativo, curioso e atlético.",
        nivelDeAtividade: "Alto",
        pelagem: "Manchada, semelhante à de um leopardo",
        id: "beng",
        img: "bengal.png"
    },
    {
        raca: "Azul Russo",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Calmo, gentil e reservado.",
        nivelDeAtividade: "Moderado",
        pelagem: "Curta, densa e prateada",
        id: "rblu",
        img: "azul-russo.png"
    },
    {
        raca: "British Shorthair",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 6,
        temperamento: "Calmo, gentil e independente.",
        nivelDeAtividade: "Baixo",
        pelagem: "Curta, densa e macia",
        id: "bsho",
        img: "british-shorthair.png"
    },
    {
        raca: "Abissínio",
        expectativaDeVida: 15,
        tamanho: "Médio",
        peso: 4,
        temperamento: "Ativo, curioso e inteligente.",
        nivelDeAtividade: "Alto",
        pelagem: "Curta, densa e marcada",
        id: "abys",
        img: "abissinio.png"
    }
];